# Generated by Django 3.2.12 on 2022-06-28 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_app', '0003_alter_massage_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='massage',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='ایمیل'),
        ),
        migrations.AlterField(
            model_name='massage',
            name='text',
            field=models.TextField(verbose_name='متن'),
        ),
        migrations.AlterField(
            model_name='massage',
            name='title',
            field=models.CharField(max_length=100, verbose_name='عنوان'),
        ),
    ]
