# Generated by Django 3.2.12 on 2022-06-28 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0002_alter_profile_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'پروفایل', 'verbose_name_plural': 'پروفایل ها'},
        ),
    ]
